plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 32

Metrics/MethodLength:
  Max: 15

Style/EmptyClassDefinition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
