#!/usr/bin/env ruby
# frozen_string_literal: true

if ENV["DEV"]
  $LOAD_PATH << File.expand_path("../lib", __dir__)
  require "pry"
end

require "virgil"

# TODO: make sure log dir exists in pwd (find a better home for this)
FileUtils.mkdir_p("log")

Virgil::CLI.start(ARGV)
